### ISSUE TITLE
Failed at the deasync@0.1.15 install script.

### ISSUE THREAD

**Issue by xiaoyu2006** [timqian/chart.xkcd#53]
**Describe the bug**
```

> deasync@0.1.15 install /Users/nemo/chart.xkcd-origin/node_modules/deasync
> node ./build.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/13.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/nemo/chart.xkcd-origin/node_modules/deasync
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.15 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**How to reproduce**
```bash
$ npm i
```

**Solution** (I'm not going to create a PR.)
```bash
$ git rm package-lock.json
$ echo '\npackage-lock.json' >> .gitignore
```

**Comment by timqian** [comment]
`npm i` works on my Mac, not sure why this is happening but
[package-lock.json is intended to be checked into source control](
https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5#:~:targetText=package%2Dlock.,regardless%20of%20intermediate%20dependency%20updates.)

**Comment by xiaoyu2006** [comment]
@timqian But code only works after deleting `package-lock.json`.

[Solution I found was rewriting the docs or deleting `package-lock.json`.](https://stackoverflow.com/questions/57605441/error-this-is-probably-not-a-problem-with-npm-there-is-likely-additional-loggi)

**Comment by Jhonneycp** [comment]
Thank you! <3 god  bless you
